// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
        int num = Integer.parseInt(args[0]);
        int b = 0;
        int s = 0;
        double sumS = 0.0;
        double sumB = 0.0;
        double ratio;

for(int i = 0; i < num; i++){ 
    double rand0 = Math.random();
	if(rand0 > 0.5){
	sumB += rand0;
	b += 1;
    } else { 
	    sumS += rand0;
        s += 1;
	}	
}
ratio = (sumS + sumB) / num;
System.out.println( "> 0.5: " +  b + " times");
System.out.println( "<= 0.5: " +  s + " times");
System.out.println( "Ratio: " +  ratio + " times");

	}
}